autoPowerOn: 85
callSign: "W R F R 8 8 6"
chargerEnable_out: 24
ct1_in: 22
DTMFOperStatus: true
gen1Name: "60A BEAST"
gen1Run_in: 18
gen1Start_out: 3
gen1Stop_out: 2
gen2Enable_out: 20
gen2Name: "wen"
gen2Run_in: 23
gennyRunning: 0
highHumidity: 35
highTemp: 83
influxBucket: "stats"
influxToken: "77KunYFbD5eDvQxZzroVc2J2m9ZuXzjjFdM_EY8d156BG9ihIbM6WZ09kDbvr6COn4KFF4cNGSaM2VFtAB9wRQ=="
influxORG: "TheRosebudExplorer"
influxURL: "http://localhost"
inverterEnable_out: 4
medHumidity: 35
medTemp: 83
ptt_out: 1
relayHatAddress: 0x10
#relayHatBus: 1
relayHatBus: "smbus.SMBus(relayHatBus)"
shuntSensor1address: 43
shunt1name: "Coach1"
shunt2name: "Coach2"
shunt3name: "Chassis"
snooze: 10
temp1_in: 4
temp2_in: 17
volt1_in: 27
