autoPowerOn: 85
callSign: "K 0 G E T"
chargerEnable_out: 24
ct1_in: 22
DTMFOperStatus: true
gen1Name: "ONAN-6500W"
gen1Run_in: 18
gen1Start_out: 3
gen1Stop_out: 2
gen2Enable_out: 20
gen2Name: "WEN-1900W"
gen2Run_in: 23
gennyRunning: 0
highHumidity: 35
highTemp: 83
influxBucket: "stats"
influxToken: "77KunYFbD5eDvQxZzroVc2J2m9ZuXzjjFdM_EY8d156BG9ihIbM6WZ09kDbvr6COn4KFF4cNGSaM2VFtAB9wRQ=="
influxORG: "TheRosebudExplorer"
influxURL: "http://localhost"
inverterSense: 10
inverterEnable_out: 4
medHumidity: 35
medTemp: 83
mqtt_host: 127.0.0.1
#mqtt_user: "dale"
mqtt_password: "paleale"
mqtt_feed: "/feeds/stats/"
mqtt_port: 1883
mqtt_username: "dale"
numberOfTries: 1
ptt_out: 27
radioCharger1_out: 20
radioCharger2_out: 21
relayHatAddress: 0x10
relayHatBus: 1
#relayHatBus: "smbus.SMBus(1)"
shuntSensor1address: 43
shunt1name: "Coach1"
shunt2name: "Coach2"
shunt3name: "Chassis"
snooze: 10
temp1_in: 22
temp2_in: 17
windowsTitle: "Control Panel"

