highHumidity: 35
highTemp: 83
medHumidity: 35
medTemp: 83
autoPowerOn: 85 
callSign: "W R F R 8 8 6"
gennyRunning: 0
snooze: 10
DTMFOperStatus: true
BigGennyName: "60A BEAST"
LittleGennyName: "wen"
PTTRelayPin: 21
BigGenStartRelayPin: 16
BigGenEnableRelayPin: 12
LittleGenEnableRelayPin: 20
ChargerEnableRelayPin: 24
InverterEnableRelayPin: 25
Temp1Pin: 4
Temp2Pin: 17
BigGenRunSense: 18
LittleGenRunSense: 23
LowVSense: 27
CT1: 22
shuntBatt1: 40 
shuntBatt2: 41
shuntCharger: 42
shuntSelfDraw: 43
