#loads default set of integrations. Do not remove.

default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Example configuration.yaml entry
mqtt:
  sensor:
    - name: "Sensor15"
      state_topic: "homeassistant/switch/Sensor0x24p15/state"
      #device_class: "sensor"
      #value_template: "{{ as_datetime(value) }}"
      unique_id: "mcp0x24p15"
      device:
        name: "Sensor0x24p15"
        identifiers:
          - "Sensor0x24p15"
    - name: "Sensor14"
      state_topic: "homeassistant/switch/Sensor0x24p14/state"
      #device_class: "sensor"
      #value_template: "{{ as_datetime(value) }}"
      unique_id: "mcp0x24p14"
      device:
        name: "Sensor0x24p14"
        identifiers:
          - "Sensor0x24p14"
    - name: "Sensor13"
      state_topic: "homeassistant/switch/Sensor0x24p13/state"
      #device_class: "sensor"
      #value_template: "{{ as_datetime(value) }}"
      unique_id: "mcp0x24p13"
      device:
        name: "Sensor0x24p13"
        identifiers:
          - "Sensor0x24p13"
    - name: "Sensor12"
      state_topic: "homeassistant/switch/Sensor0x24p12/state"
      #device_class: "sensor"
      #value_template: "{{ as_datetime(value) }}"
      unique_id: "mcp0x24p12"
      device:
        name: "Sensor0x24p12"
        identifiers:
          - "Sensor0x24p12"
    - name: "Sensor11"
      state_topic: "homeassistant/switch/Sensor0x24p11/state"
      #device_class: "sensor"
      #value_template: "{{ as_datetime(value) }}"
      unique_id: "mcp0x24p11"
      device:
        name: "Sensor0x24p11"
        identifiers:
          - "Sensor0x24p11"
  switch:
    - name: "External Generators"
      state_topic: "homeassistant/switch/Sensor0x24p9/state"
      command_topic: "homeassistant/switch/Sensor0x24p9/set"
      payload_on: "ON"
      payload_off: "OFF"
      optimistic: false
      qos: 1
      retain: true
      device:
        name: "externalGenerators"
        identifiers:
          - "Sensor0x24p9"
    - name: "Inverter"
      state_topic: "homeassistant/switch/Sensor0x24p10/state"
      command_topic: "homeassistant/switch/Sensor0x24p10/set"
      payload_on: "ON"
      payload_off: "OFF"
      optimistic: false
      qos: 1
      retain: true
      device:
        name: "externalGenerators"
        identifiers:
          - "Sensor0x24p10"